name: Sync Repo with Google Drive

on:
  push:

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Determine Sync Directory
        id: sync_dir
        run: |
          REPO_OWNER=$(echo "${GITHUB_REPOSITORY}" | cut -d'/' -f1)
          REPO_NAME=$(echo "${GITHUB_REPOSITORY}" | cut -d'/' -f2)
          BRANCH_NAME=$(echo "${GITHUB_REF#refs/heads/}" | tr '/' '_')
          DESTINATION_FOLDER="${REPO_OWNER}/${REPO_NAME}/${BRANCH_NAME}"

          echo "DESTINATION_FOLDER=${DESTINATION_FOLDER}" >> $GITHUB_OUTPUT

      - name: Sync with Google Drive
        uses: AnimMouse/setup-rclone@v1
        with:
          rclone_config: |
            ${{ secrets.RCLONE_CONFIG }}
          disable_base64: true
      - run: |
          echo "Syncing with ${{ steps.sync_dir.outputs.DESTINATION_FOLDER }}"
          rclone sync . "gdrive:${{ steps.sync_dir.outputs.DESTINATION_FOLDER }}" -P -c
