name: Backup npm Project to Google Drive

on:
  push:
    branches:
      - main # Change to your default branch if different

jobs:
  backup:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Ensure full history is fetched if needed

      - name: Determine Backup Directory
        id: backup_dir
        run: |
          REPO_OWNER=$(echo "${GITHUB_REPOSITORY}" | cut -d'/' -f1)
          REPO_NAME=$(echo "${GITHUB_REPOSITORY}" | cut -d'/' -f2)
          BRANCH_NAME=$(echo "${GITHUB_REF#refs/heads/}" | tr '/' '_')
          DESTINATION_FOLDER="${REPO_OWNER}/${REPO_NAME}/${SANITIZED_BRANCH_NAME}"

          echo "DESTINATION_FOLDER=${DESTINATION_FOLDER}" >> $GITHUB_OUTPUT

      - name: Backup to Google Drive
        uses: AnimMouse/setup-rclone@v1
        with:
          rclone_config: ${{ secrets.RCLONE_CONFIG }}
      - run: |
          echo "Creating destination folder: ${{ steps.backup_dir.outputs.DESTINATION_FOLDER }}"
          rclone mkdir "gdrive:${{ steps.backup_dir.outputs.DESTINATION_FOLDER }}"

          echo "Uploading tracked files to ${{ steps.backup_dir.outputs.DESTINATION_FOLDER }}"
          rclone copy . "gdrive:${{ steps.backup_dir.outputs.DESTINATION_FOLDER }}" -P

      - name: Clean Up
        run: |
          echo "Backup completed and uploaded to Google Drive."
