name: Sync Repo with Google Drive

on:
  push:

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Ensure full history is fetched if needed

      - name: Determine Backup Directory
        id: backup_dir
        run: |
          REPO_OWNER=$(echo "${GITHUB_REPOSITORY}" | cut -d'/' -f1)
          REPO_NAME=$(echo "${GITHUB_REPOSITORY}" | cut -d'/' -f2)
          BRANCH_NAME=$(echo "${GITHUB_REF#refs/heads/}" | tr '/' '_')
          DESTINATION_FOLDER="${REPO_OWNER}/${REPO_NAME}/${BRANCH_NAME}"

          echo "DESTINATION_FOLDER=${DESTINATION_FOLDER}" >> $GITHUB_OUTPUT

      - name: Sync with Google Drive
        uses: AnimMouse/setup-rclone@v1
        with:
          rclone_config: |
            ${{ secrets.RCLONE_CONFIG }}
          disable_base64: true
      - run: |
          echo "Creating destination folder: ${{ steps.backup_dir.outputs.DESTINATION_FOLDER }}"
          rclone mkdir "gdrive:${{ steps.backup_dir.outputs.DESTINATION_FOLDER }}"

          echo "Syncing with ${{ steps.backup_dir.outputs.DESTINATION_FOLDER }}"
          rclone sync . "gdrive:${{ steps.backup_dir.outputs.DESTINATION_FOLDER }}" -P
